### ISSUE TITLE
go get failed

### ISSUE THREAD

**Issue by teddy1004** [peter-edge/lion-go#5]
when I input `go get go.pedge.io/lion` , I got the following error

```
package go.pedge.io/lion: unrecognized import path "go.pedge.io/lion" (parse https://go.pedge.io/lion?go-get=1: no go-import meta tags ())
```

seems likes the host server is down

**Comment by peter-edge** [comment]
I'm sorry, I recently switched hosting providers and I didn't find out about this! Should be back up now, my apologies again.

**Comment by teddy1004** [comment]
@peter-edge the server down again

**Comment by peter-edge** [comment]
It's due to outages with https://sloppy.io, I'm doing all I can to ping them to get this back up but they have been down a lot recently https://status.sloppy.io and they recently sent an email saying they're suspending accounts at their will to make sure some customers stay up. I'll keep you updated.

**Comment by peter-edge** [comment]
Should be back up now.
